const Data= {
      "1":{
        "id":1,
        "orderno":22,
        "price":220,
        "name":"Zaryab1",
        "address":"Shadman 14-b",
        "orderitem":"Daal Chawal",
        "status":"Delivered",
        "ordertype":"Cash on Delivery",
      },
      "2":{
        "id":2,
        "orderno":19,
        "price":220,
        "name":"Zaryab2",
        "address":"Shadman 14-b",
        "orderitem":"Daal Chawal",
        "status":"Pending",
        "ordertype":"Cash on Delivery",
      },
      "6":{
        "id":1,
        "orderno":22,
        "price":220,
        "name":"Zaryab3",
        "address":"Shadman 14-b",
        "orderitem":"Daal Chawal",
        "status":"Delivered",
        "ordertype":"Cash on Delivery",
      },
      "7":{
        "id":2,
        "orderno":19,
        "price":220,
        "name":"Zaryab4",
        "address":"Shadman 14-b",
        "orderitem":"Daal Chawal",
        "status":"Pending",
        "ordertype":"Cash on Delivery",
      },
      "3":{
        "id":3,
        "orderno":18,
        "price":220,
        "name":"Zaryab5",
        "address":"Shadman 14-b",
        "orderitem":"Daal Chawal",
        "status":"Delivered",
        "ordertype":"Cash on Delivery",
      },
      "4":{
        "id":4,
        "orderno":23,
        "price":220,
        "name":"Zaryab6",
        "address":"Shadman 14-b",
        "orderitem":"Pizza",
        "status":"Pending",
        "ordertype":"Cash on Delivery",
      },
      "5":{
        "id":4,
        "orderno":223,
        "price":220,
        "name":"Zaryab7",
        "address":"Shadman 14-b",
        "orderitem":"Pizza",
        "status":"Pending",
        "ordertype":"Cash on Delivery",
      },
    
  }

export default Data;