export const Status = {
  RECIEVED: 'RECIEVED',
  COOKING: 'COOKING',
  FINISHED_COOKING: 'FINISHED_COOKING',
  PICKED_BY_RIDER: 'PICKED_BY_RIDER',
  DELIVERED: 'DELIVERED',
};

export const OrderTypes = {
  SIMPLE: 'SIMPLE',
  SCHEDULED: 'SCHEDULED',
  WITH_PLAN: 'WITH_PLAN',
};

